###########################################################
# Paths

# Path where ETL creates raw dumps of dataset tables
dataset_dump_path: /var/lib/datacamp/dumps

# Keys
captcha_private_key: XXX
captcha_public_key: XXX